spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none;
    properties:
      hibernate:
        jdbc:
          batch_size: 20
server:
  port: ${APP_PORT:8080}
jwt:
  expiration: ${JWT_EXPIRATION_SECOND:30M}
  secret: ${JWT_SECRET:secret}
springdoc:
  swagger-ui:
    path: /api/doc/swagger-ui.html
  api-docs:
    path: /api/doc/v3/api-docs
  default-produces-media-type: application/json