spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update;
server:
  port: ${APP_PORT}
jwt:
  expiration: ${JWT_EXPIRATION_MILLI}
  secret: ${JWT_SECRET}